apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timeslot-data
  namespace: timeslot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard  # uncomment and set as needed
